controllers/CommoditiesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Commodities;
use app\models\CommoditiesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use arturoliveira\ExcelView;

/**
 * CommoditiesController implements the CRUD actions for Commodities model.
 */
class CommoditiesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Commodities models.
     * @return mixed
     */
    
    public function actionExport() {
        $searchModel =  new CommoditiesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        ExcelView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'fullExportType'=> 'xlsx', //can change to html,xls,csv and so on
            'grid_mode' => 'export',
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

            // 'commodity_id',
            'commodity_code',
            'commodity_name',
            'commodity_created_date',

              ],
        ]);
    }
    public function actionIndex()
    {
       $this->layout =  $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $searchModel = new CommoditiesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = [
        'pageSize' => 8,
            ];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Commodities model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Commodities model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $model = new Commodities();

        if ($model->load(Yii::$app->request->post())) {
            $model->commodity_created_date = new Expression('NOW()');
            $model->save();
            return $this->redirect(['view', 'id' => $model->commodity_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Commodities model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->commodity_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Commodities model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Commodities model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Commodities the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Commodities::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
           

controllers/MarketsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Markets;
use app\models\MarketsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use arturoliveira\ExcelView;
/**
 * MarketsController implements the CRUD actions for Markets model.
 */
class MarketsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Markets models.
     * @return mixed
     */
      public function actionExport() {
        $searchModel =   new MarketsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        ExcelView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'fullExportType'=> 'xlsx', //can change to html,xls,csv and so on
            'grid_mode' => 'export',
            'columns' => [
                 ['class' => 'yii\grid\SerialColumn'],

            //'market_id',
            'market_code',
            'market_name',
            'market_location',
            'market_created_date',

              ],
        ]);
    }
    public function actionIndex()
    {
         $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $searchModel = new MarketsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = [
        'pageSize' => 8,
    ];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Markets model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
         $this->layout = "@yiister/gentelella/views/layouts/main.php";
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Markets model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $model = new Markets();

        if ($model->load(Yii::$app->request->post())) {
            $model->market_created_date = new Expression('NOW()');
            $model->save();
            return $this->redirect(['view', 'id' => $model->market_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Markets model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->market_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Markets model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Markets model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Markets the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Markets::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/TraderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Trader;
use app\models\Tradercommodities;
use app\models\TraderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use linslin\yii2\curl;
use yii\web\Session;
use yii\data\Pagination;
use arturoliveira\ExcelView;


/**
 * TraderController implements the CRUD actions for Trader model.
 */
class TraderController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Trader models.
     * @return mixed
     */
      public function actionExport() {
        $searchModel =  new TraderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        ExcelView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'fullExportType'=> 'xlsx', //can change to html,xls,csv and so on
            'grid_mode' => 'export',
            'columns' => [
                 ['class' => 'yii\grid\SerialColumn'],
            [ 'attribute'=>'market_id',
             'value'=>'market.market_name',
                
            ],
            
            //'trader_id',
            'fName',
            'sName',
            'email',
            'id_No',
            'date',
            'phone',
            'stall_No',
            'passport_photo_no',
            'trader_commodity_id',
              ],
        ]);
    }

    public function actionIndex() {


        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $searchModel = new TraderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination = [
        'pageSize' => 8,
    ];

        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Trader model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Trader model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $session = Yii::$app->session;
        $model = new Trader();
        $trader_commodity=array();
       
        
        if ($model->load(Yii::$app->request->post())) {
            $trader_commodity = $_POST['Trader']['trader_commodity_id'];
            
           // var_dump($trader_commodity); exit;
            //foreach($trader_commodity as $key => $value ):
        
            $model->date = new Expression('NOW()');
            //$trader_commodity = json_encode($_POST['Trader']['trader_commodity_id']);
            
           
           //echo $trader_commodity; exit;
           //$trader_commodity = preg_replace('/\\\"/',"\"",$trader_commodity);
            $model->trader_commodity_id = implode(',',$trader_commodity);
            
           
//            $curl = new curl\Curl();
//            $response = $curl->setOption(
//                            CURLOPT_POSTFIELDS, http_build_query(array(
//                        'grant_type' => "agency",
//                        'username' => "teller1.branch1@agency.com",
//                        'password' => 'p@ssw0rd'
//                                    )
//                    ))
//                    ->post('http://192.168.11.22/jambopayservices/token');
//            $res = json_decode($response);
//            if ($res !== NULL) {
//                $token = $res->access_token;
//
//
//                $request = Yii::$app->request->post();
//                $username = $request['Trader']['phone'];
//                $pino = '0000';
//                $email = $request['Trader']['email'];
//                $firstname = $request['Trader']['fName'];
//                //var_dump($request['Trader']['fName']); die();
//                $secondname = $request['Trader']['sName'];
//                $idno = $request['Trader']['id_No'];
//                $params = [
//                    'Stream' => "wallet",
//                    'PhoneNumber' => $username,
//                    'Pin' => $pino,
//                    'Email' => $email,
//                    'FirstName' => $firstname,
//                    'LastName' => $secondname,
//                    'IDNumber' => $idno
//                ];
//                $headers = [
//                    'Authorization: bearer ' . $token,
//                    'app_key: 7E9D236F-67E2-E411-8285-B8EE657EAEBC'
//                ];
//
//
//                $resWallet = $curl->setOption(
//                                CURLOPT_POSTFIELDS, http_build_query($params
//                        ))
//                        ->setOption(CURLOPT_HTTPHEADER, $headers)
//                        ->post('http://192.168.11.22/jambopayservices/api/Wallet/PostWalletRegister');
//                $session = Yii::$app->session;
//
//
//                $session['error_object'] = json_decode($resWallet);
//                //var_dump($session['error_object']); die();
//                $error = isset($session['error_object']) ? $session['error_object'] : null;
//                //var_dump($error->ErrorType); die();
//                if (isset($error->ErrorType)) {
//                    \Yii::$app->getSession()->setFlash('error-message', $error->Message);
//                    $this->redirect(['create']);
//                } else {
//                    \Yii::$app->getSession()->setFlash('success-message', "You have successfully created a Jambopay wallet");
//                    
//                }
             
         
                 if($model->save()){
                     $trader_id=$model->getPrimaryKey();
                     
                     foreach($trader_commodity as $key => $val)
                         {
                         $commoditiesModel=new Tradercommodities();
                         $commoditiesModel->trader_id=$trader_id;
                         $commoditiesModel->trader_id_no=$model->id_No;
                         $commoditiesModel->traderId=  rand(10000, 100000);
                         $commoditiesModel->commodity_id=7;
                         $commoditiesModel->save();                        
                     }
                      return $this->redirect(['view', 'id' => $model->trader_id]);
                     
                 }
                
                    
         
      
        
        //endforeach;
        
         
        }
         else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        
        }
        
    }

    /**
     * Updates an existing Trader model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->trader_id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Trader model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
       $this->layout = "@yiister/gentelella/views/layouts/main.php";
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Trader model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Trader the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Trader::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/layouts/app.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use yii\helpers\Html;
use kartik\sidenav\SideNav;
use yii\widgets\Breadcrumbs;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use kartik\widgets\Spinner;
use richardfan\widget\JSRegister;

$url = Yii::$app->getUrlManager();
$item = Yii::$app->controller->id . "/" . Yii::$app->controller->action->id;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body>

   
<?php $this->beginBody() ?>
<div class="menubar">
<?php
    NavBar::begin([
        'brandLabel' => 'E-NZOIA',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
  
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>
    </div>
 <div id="breadcrumbs">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
    </div>

<div class=" col-xs-5 col-sm-4 col-lg-3 menu">
<?=

    SideNav::widget([
        'type' => SideNav::TYPE_DEFAULT,
        'heading' => '',
        'items' => [
            ['url' => $url->createUrl(['/site/index']), 'label' => 'Home', 'icon' => 'th', 'active' => ($item == 'site/index')],
            
           
            [
                'label' => 'Traders',
                'icon' => 'th',
                'items' => [
                    ['label' => 'View Traders', 'icon' => 'list', 'url' => $url->createUrl(['/trader/index']), 'active' => ($item == 'trader/index')],
                    ['label' => 'Create Traders', 'icon' => 'list', 'url' => $url->createUrl(['/trader/create']), 'active' => ($item == '/trader/create')],
                ],
            ],
            [
                'label' => 'Markets',
                'icon' => 'th',
                'items' => [
                    ['label' => 'View Markets', 'icon' => 'list', 'url' => $url->createUrl(['/markets/index']), 'active' => ($item == 'markets/index')],
                    ['label' => 'Create Markets', 'icon' => 'list', 'url' => $url->createUrl(['/markets/create']), 'active' => ($item == 'markets/create')],
                ],
            ],
            
            [
                'label' => 'Commodities',
                'icon' => 'th',
                'items' => [
                    ['label' => 'View Commodities', 'icon' => 'list', 'url' => $url->createUrl(['/commodities/index']), 'active' => ($item == 'commodities/index')],
                    ['label' => 'Create Commodities', 'icon' => 'file', 'url' => $url->createUrl(['/commodities/create']), 'active' => ($item == 'commodities/create')],
                    //['label' => 'E-Learning', 'icon' => 'file', 'url' => 'http://library.kasneb.or.ke/', 'template' => '<a href="{url}" target="_blank">{icon}{label}</a>'],
               ],
            ],
            [
                'label' => 'Trader Commodities',
                'icon' => 'th',
                'items' => [
                    ['label' => 'View Trader Commodities', 'icon' => 'list', 'url' => $url->createUrl(['/tradercommodities/index']), 'active' => ($item == '/tradercommodities/index')],
                  
                    ['label' => 'Add Trader Commodities', 'icon' => 'list', 'url' => $url->createUrl(['/tradercommodities/create']), 'active' => ($item == '/tradercommodities/create')],
                    
                ],
            ], 
            [
                'label' => 'User manager',
                'icon' => 'user',
                'items' => [
                    ['label' => 'View users', 'icon' => 'list', 'url' => $url->createUrl(['user/admin/index']), 'active' => ($item == 'user/admin/index')],
                  
                    ['label' => 'Create users', 'icon' => 'list', 'url' => $url->createUrl(['user/admin/create']), 'active' => ($item == 'user/admin/create')],
                    
                ],
            ], 
            
        ],
    ]);
    ?>
</div>
    
    <div class="col-xs-7 col-sm-8 col-lg-9">
      
        <?= $content ?>
    </div>




<?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>

views/layouts/login.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use yii\helpers\Html;




AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">


    <div class="container">
    
    
        <?= $content ?>
    </div>
</div>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;


AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
 <?php
    NavBar::begin([
        'brandLabel' => 'E-NZOIA',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
    
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
   
        <?= $content ?>
    </div>
</div>



<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>